## Basic Numpy Operations

In [7]:
import numpy as np

In [8]:
# a[:] --- copy the whole array 

In [9]:
a = [1,2,11,6,8,18,2]

na = np.array(a)

print(type(na))

<class 'numpy.ndarray'>


In [10]:
print(na.shape) # its a rank 1 numpy array with 7 elements

(7,)


In [11]:
#lets print put an element at index 2

print(na[2])

11


In [12]:
# isolate an entire chunk based on start index-end index
#print out values at start to end-1 location

print(na[1:5])

[ 2 11  6  8]


In [13]:
#use a step of two

print(na[1:5:2])

[2 6]


In [14]:
#negative index
#print out values at start to end-1 index location

print(na[-7:-1])

[ 1  2 11  6  8 18]


In [15]:
#print last item

print(na[-1])

2


In [18]:
# items starts at one index and all the way to the end

print(na[4:])

[ 8 18  2]


In [19]:
#print elements from beginning through end-1

print(na[:6])

[ 1  2 11  6  8 18]


In [24]:
#copy aan array

b = na[:]

print(b)

[ 1  2 11  6  8 18  2]


In [25]:
#concatenate two arrays

x = np.array([1,2,3,4])

y = np.array([3,4,5,6])

z = np.concatenate([x,y])

print(z)

[1 2 3 4 3 4 5 6]


### Multi-dimensional array operations

In [26]:
arr = [[1,2,3,4],[3,4,5,6],[5,6,7,8],[7,8,9,10]]

narr = np.array(arr)

print(narr)

[[ 1  2  3  4]
 [ 3  4  5  6]
 [ 5  6  7  8]
 [ 7  8  9 10]]


In [27]:
#print second row at row index 1

print(narr[1])

[3 4 5 6]


In [30]:
print(narr[1,0]) #print first element of second row

3


In [31]:
narr[3,3] = 1 # replace element at 4th index of 3rd row

print(narr)

[[1 2 3 4]
 [3 4 5 6]
 [5 6 7 8]
 [7 8 9 1]]


In [33]:
#print the last row

print(narr[-1])

[7 8 9 1]


In [34]:
#print rows and columns

print(narr[1:4,2:4])

[[5 6]
 [7 8]
 [9 1]]


In [35]:
# concatenation row and column wise

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

c = np.concatenate([a,b])

print(c)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [36]:
d = np.array([[11,12,13,14]])

narr1 = np.concatenate([narr,d])
print(narr1)

[[ 1  2  3  4]
 [ 3  4  5  6]
 [ 5  6  7  8]
 [ 7  8  9  1]
 [11 12 13 14]]


In [37]:
narr = narr1[:]
print(narr)

[[ 1  2  3  4]
 [ 3  4  5  6]
 [ 5  6  7  8]
 [ 7  8  9  1]
 [11 12 13 14]]


In [38]:
print(narr)

[[ 1  2  3  4]
 [ 3  4  5  6]
 [ 5  6  7  8]
 [ 7  8  9  1]
 [11 12 13 14]]
