## Vector Arithmetic

In [2]:
import numpy as np

In [3]:
#create numpy arrays
x = np.array([1,2,3])
y = np.array([2,3,4])

### addition

In [4]:
print(x+y)

[3 5 7]


In [5]:
#scalar addition
print(x+2)

[3 4 5]


### subtract

In [6]:
print(y-x)

[1 1 1]


### multiply

In [10]:
#hadmard product

print(x*y)

[ 2  6 12]


In [8]:
#dot product
print(np.dot(y,x))

20


In [14]:
print(y/x)

[2.         1.5        1.33333333]
