## Matrix Arithmetic

In [1]:
import numpy as np

In [2]:
x=np.matrix([[1, 2], [3, 4]])

y=np.matrix([[5, 3], [8, 7]])
#Numpy matrices are strictly 2-dimensional, while numpy arrays (ndarrays) are N-dimensional. 
#provide a convenient notation for matrix multiplication

In [3]:
print(type(y))

<class 'numpy.matrixlib.defmatrix.matrix'>


In [4]:
print(x)

[[1 2]
 [3 4]]


In [5]:
print(x+y)

[[ 6  5]
 [11 11]]


In [6]:
print(x*3)

[[ 3  6]
 [ 9 12]]


## Subtraction

In [7]:
print(x-y)

[[-4 -1]
 [-5 -3]]


## Multiplication

In [8]:
A=np.matrix([[1, 2], [3, 4]])

print(A)

[[1 2]
 [3 4]]


In [9]:
#haddmard multiplication
print (A*A)

[[ 7 10]
 [15 22]]


In [10]:
#elemant wise multiplication
print(np.multiply(A,A))

[[ 1  4]
 [ 9 16]]


## Inverse

In [11]:
from numpy.linalg import inv

In [12]:
print(inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


## Transpose

In [13]:
print(A.T) #flip rows with columns 

[[1 3]
 [2 4]]


## Broadcasting

### Perform arithmetic operations on different shaped arrays
### smaller array is broadcast across the larger array to ensure shape consistency 
### Rules:

### (1) One dimension (either column or row) should have the same dimensions for both arrays
### (2) The lower dimension array should be a 1D array


In [14]:
A = np.arange(20).reshape(5,4)
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [15]:
print(type(A))

<class 'numpy.ndarray'>


In [16]:
B = np.arange(5)
print(B)

[0 1 2 3 4]


In [19]:
#either rows are equal or columns are equal to ensure shape consistency
B = B.reshape(5,1) #5 rows 

print(A+B)

[[ 0  1  2  3]
 [ 5  6  7  8]
 [10 11 12 13]
 [15 16 17 18]
 [20 21 22 23]]


In [20]:
# multiplication
print(A*B)

[[ 0  0  0  0]
 [ 4  5  6  7]
 [16 18 20 22]
 [36 39 42 45]
 [64 68 72 76]]
