## Numpy is an n dimensional array object or ** ndarray ** 
## which provides a fast and efficent way of storing homogenous data

## we can have ndarray with 1 dimension or 1 row and these are rank 1 arrays
## or we can have multi-dimnesional rarrays with more than one row [[row1, row2],[row3,row4]]

In [1]:
import numpy as np

In [2]:
##Rank 1 array

arr1 = [3,4,5,6,7]

print(type(arr1))

<class 'list'>


In [3]:
narr1 = np.array(arr1)
print(narr1)
print(type(narr1))

[3 4 5 6 7]
<class 'numpy.ndarray'>


In [4]:
# multidimensional array

arr2 = [[1,2,3,4],[3,4,5,6]]

narr2 = np.array(arr2)

print((narr2))

[[1 2 3 4]
 [3 4 5 6]]


In [5]:
arr3 = [[1,2,3,4],[3,4,5,6],[5,6,7,8]]

narr3 = np.array(arr3)

print(narr3)

[[1 2 3 4]
 [3 4 5 6]
 [5 6 7 8]]


In [6]:
print(narr3.shape)

(3, 4)


In [7]:
#2*2 array with 0s
zero = np.zeros((2,2))
print(zero)

[[0. 0.]
 [0. 0.]]


In [12]:
#2*2 array with 5
full = np.full((2,2),5)
print(full)

[[5 5]
 [5 5]]


In [9]:
#2*2 array with daiagonal 1
eye = np.eye(2,2)
print(eye)

[[1. 0.]
 [0. 1.]]


In [10]:
#3*3 array with diagonal 1

eye = np.eye(3,3)
print(eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
