## Solve equations

In [60]:
# Study linear algebra using nu;py

In [61]:
import numpy as np
from numpy.linalg import inv

In [62]:
A = np.matrix([[2,1],[1,-1]]) #np.array

In [63]:
b = np.matrix([4,-1]) #np.array
print(b)

[[ 4 -1]]


In [64]:
b = b.reshape(2,1) #no need in case of array
#print(b)

In [65]:
Ainv = inv(A) #same with array
#print(Ainv)

In [66]:
ans = Ainv*b #Ainv.dot(b) gives the answer

In [67]:
print(ans)

[[1.]
 [2.]]


In [68]:
#shortcut method

np.linalg.solve(A,b)

matrix([[1.],
        [2.]])

## Some basic stats with numpy

In [69]:
arr = [[1,2,3,4],[3,4,5,6],[7,8,9,6],[12,7,10,9],[2,11,8,10]]

In [70]:
narr = np.array(arr)
print(narr)

[[ 1  2  3  4]
 [ 3  4  5  6]
 [ 7  8  9  6]
 [12  7 10  9]
 [ 2 11  8 10]]


In [71]:
narr.sum() #sum all values of the array

127

In [72]:
narr.sum(axis = 0) #column-wise sum

array([25, 32, 35, 35])

In [73]:
narr.sum(axis = 1) #row-wise sum

array([10, 18, 30, 38, 31])

In [74]:
# means an medians are measures of central tendency 

narr.mean(axis = 0) # column means

array([5. , 6.4, 7. , 7. ])

In [78]:
np.mean(narr,axis = 1) #row means

array([2.5 , 4.5 , 7.5 , 9.5 , 7.75])

In [84]:
# row median

np.median(narr,axis = 1)
#np.median(narr)

array([2.5, 4.5, 7.5, 9.5, 9. ])

In [76]:
# variance in the data

np.std(narr,axis = 1) #standard devaiation

array([1.11803399, 1.11803399, 1.11803399, 1.80277564, 3.49106001])

In [82]:
#standard deviation of whole array
np.std(narr)

3.182373328193912

In [89]:
#percentile-value below which a given percentage of observations
np.percentile(narr,50,axis = 1) #50th percentile
#np.percentile(narr,50)#whole data

array([2.5, 4.5, 7.5, 9.5, 9. ])